// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpaymvmdowzqirkqpxsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwYXltdm1kb3d6cWlya3FweHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjU4NTUsImV4cCI6MjA3MzQwMTg1NX0.iWylxmJ-nuyQqHW4FiDf9micbz-byHqUhI0YLPMpfWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});